# Generated by Django 4.2.1 on 2023-07-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_rename_name_comment_comment_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
    ]
